version: '3'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SERVER_PORT=8080
      - BASE_URL=http://localhost:8080
      - API_KEY=your-api-key-here
      - POSTGRES_URL=postgres://postgres:postgres@postgres:5432/urlshortener?sslmode=disable
      - VALKEY_ADDR=valkey:6379
      - VALKEY_PASSWORD=
      - VALKEY_DB=0
      - VALKEY_TTL=24h
    depends_on:
      - postgres
      - valkey
    restart: unless-stopped

  postgres:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=urlshortener
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  valkey:
    image: valkey/valkey:latest
    ports:
      - "6379:6379"
    volumes:
      - valkey_data:/data
    restart: unless-stopped

volumes:
  postgres_data:
  valkey_data:
