// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: clicks.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getClicksByBrowser = `-- name: GetClicksByBrowser :many
SELECT browser, COUNT(*) AS count FROM clicks
WHERE url_short = $1
GROUP BY browser
`

type GetClicksByBrowserRow struct {
	Browser pgtype.Text `json:"browser"`
	Count   int64       `json:"count"`
}

func (q *Queries) GetClicksByBrowser(ctx context.Context, urlShort string) ([]GetClicksByBrowserRow, error) {
	rows, err := q.db.Query(ctx, getClicksByBrowser, urlShort)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetClicksByBrowserRow{}
	for rows.Next() {
		var i GetClicksByBrowserRow
		if err := rows.Scan(&i.Browser, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getClicksByDevice = `-- name: GetClicksByDevice :many
SELECT device, COUNT(*) AS count FROM clicks
WHERE url_short = $1
GROUP BY device
`

type GetClicksByDeviceRow struct {
	Device pgtype.Text `json:"device"`
	Count  int64       `json:"count"`
}

func (q *Queries) GetClicksByDevice(ctx context.Context, urlShort string) ([]GetClicksByDeviceRow, error) {
	rows, err := q.db.Query(ctx, getClicksByDevice, urlShort)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetClicksByDeviceRow{}
	for rows.Next() {
		var i GetClicksByDeviceRow
		if err := rows.Scan(&i.Device, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getClicksByLocation = `-- name: GetClicksByLocation :many
SELECT location, COUNT(*) AS count FROM clicks
WHERE url_short = $1
GROUP BY location
`

type GetClicksByLocationRow struct {
	Location pgtype.Text `json:"location"`
	Count    int64       `json:"count"`
}

func (q *Queries) GetClicksByLocation(ctx context.Context, urlShort string) ([]GetClicksByLocationRow, error) {
	rows, err := q.db.Query(ctx, getClicksByLocation, urlShort)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetClicksByLocationRow{}
	for rows.Next() {
		var i GetClicksByLocationRow
		if err := rows.Scan(&i.Location, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getClicksByShort = `-- name: GetClicksByShort :many
SELECT id, url_id, url_short, ip, location, browser, device, timestamp
FROM clicks
WHERE url_short = $1
ORDER BY timestamp DESC
`

func (q *Queries) GetClicksByShort(ctx context.Context, urlShort string) ([]Click, error) {
	rows, err := q.db.Query(ctx, getClicksByShort, urlShort)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Click{}
	for rows.Next() {
		var i Click
		if err := rows.Scan(
			&i.ID,
			&i.UrlID,
			&i.UrlShort,
			&i.Ip,
			&i.Location,
			&i.Browser,
			&i.Device,
			&i.Timestamp,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTotalClicks = `-- name: GetTotalClicks :one
SELECT COUNT(*) FROM clicks WHERE url_short = $1
`

func (q *Queries) GetTotalClicks(ctx context.Context, urlShort string) (int64, error) {
	row := q.db.QueryRow(ctx, getTotalClicks, urlShort)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const hasRecentClick = `-- name: HasRecentClick :one
SELECT EXISTS(
    SELECT 1 FROM clicks
    WHERE url_short = $1
    AND ip = $2
    AND browser = $3
    AND device = $4
    AND timestamp > NOW() - INTERVAL '1 hour'
)
`

type HasRecentClickParams struct {
	UrlShort string      `json:"url_short"`
	Ip       string      `json:"ip"`
	Browser  pgtype.Text `json:"browser"`
	Device   pgtype.Text `json:"device"`
}

func (q *Queries) HasRecentClick(ctx context.Context, arg HasRecentClickParams) (bool, error) {
	row := q.db.QueryRow(ctx, hasRecentClick,
		arg.UrlShort,
		arg.Ip,
		arg.Browser,
		arg.Device,
	)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const storeClick = `-- name: StoreClick :one
INSERT INTO clicks (url_id, url_short, ip, location, browser, device, timestamp)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, url_id, url_short, ip, location, browser, device, timestamp
`

type StoreClickParams struct {
	UrlID     int64            `json:"url_id"`
	UrlShort  string           `json:"url_short"`
	Ip        string           `json:"ip"`
	Location  pgtype.Text      `json:"location"`
	Browser   pgtype.Text      `json:"browser"`
	Device    pgtype.Text      `json:"device"`
	Timestamp pgtype.Timestamp `json:"timestamp"`
}

func (q *Queries) StoreClick(ctx context.Context, arg StoreClickParams) (Click, error) {
	row := q.db.QueryRow(ctx, storeClick,
		arg.UrlID,
		arg.UrlShort,
		arg.Ip,
		arg.Location,
		arg.Browser,
		arg.Device,
		arg.Timestamp,
	)
	var i Click
	err := row.Scan(
		&i.ID,
		&i.UrlID,
		&i.UrlShort,
		&i.Ip,
		&i.Location,
		&i.Browser,
		&i.Device,
		&i.Timestamp,
	)
	return i, err
}
