// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Click struct {
	ID        int32            `json:"id"`
	UrlID     int64            `json:"url_id"`
	UrlShort  string           `json:"url_short"`
	Ip        string           `json:"ip"`
	Location  pgtype.Text      `json:"location"`
	Browser   pgtype.Text      `json:"browser"`
	Device    pgtype.Text      `json:"device"`
	Timestamp pgtype.Timestamp `json:"timestamp"`
}

type Url struct {
	ID               int32            `json:"id"`
	Original         string           `json:"original"`
	Short            string           `json:"short"`
	Title            pgtype.Text      `json:"title"`
	CreatedAt        pgtype.Timestamp `json:"created_at"`
	ExpiresAt        pgtype.Timestamp `json:"expires_at"`
	Clicks           int64            `json:"clicks"`
	CreatorReference pgtype.Text      `json:"creator_reference"`
	DeletedAt        pgtype.Timestamp `json:"deleted_at"`
}

type UrlHistory struct {
	ID         int32            `json:"id"`
	UrlID      int64            `json:"url_id"`
	UrlShort   string           `json:"url_short"`
	Action     string           `json:"action"`
	OldValue   []byte           `json:"old_value"`
	NewValue   []byte           `json:"new_value"`
	ModifiedAt pgtype.Timestamp `json:"modified_at"`
	ModifiedBy pgtype.Text      `json:"modified_by"`
}
