// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateURL(ctx context.Context, arg CreateURLParams) (Url, error)
	GetClicksByBrowser(ctx context.Context, urlShort string) ([]GetClicksByBrowserRow, error)
	GetClicksByDevice(ctx context.Context, urlShort string) ([]GetClicksByDeviceRow, error)
	GetClicksByLocation(ctx context.Context, urlShort string) ([]GetClicksByLocationRow, error)
	GetClicksByShort(ctx context.Context, urlShort string) ([]Click, error)
	GetTotalClicks(ctx context.Context, urlShort string) (int64, error)
	GetURLByOriginal(ctx context.Context, original string) (Url, error)
	GetURLByShort(ctx context.Context, short string) (Url, error)
	GetURLsByCreator(ctx context.Context, creatorReference pgtype.Text) ([]Url, error)
	HardDeleteURL(ctx context.Context, short string) (int64, error)
	HasRecentClick(ctx context.Context, arg HasRecentClickParams) (bool, error)
	IncrementClicks(ctx context.Context, short string) (int64, error)
	LogURLHistory(ctx context.Context, arg LogURLHistoryParams) (UrlHistory, error)
	SoftDeleteURL(ctx context.Context, short string) (int64, error)
	SoftDeleteURLWithCreator(ctx context.Context, arg SoftDeleteURLWithCreatorParams) (int64, error)
	StoreClick(ctx context.Context, arg StoreClickParams) (Click, error)
	UpdateURL(ctx context.Context, arg UpdateURLParams) (Url, error)
	UpdateURLWithCreator(ctx context.Context, arg UpdateURLWithCreatorParams) (Url, error)
}

var _ Querier = (*Queries)(nil)
