// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: url_history.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const logURLHistory = `-- name: LogURLHistory :one
INSERT INTO url_history (url_id, url_short, action, old_value, new_value, modified_at, modified_by)
VALUES ($1, $2, $3, $4, $5, NOW(), $6)
RETURNING id, url_id, url_short, action, old_value, new_value, modified_at, modified_by
`

type LogURLHistoryParams struct {
	UrlID      int64       `json:"url_id"`
	UrlShort   string      `json:"url_short"`
	Action     string      `json:"action"`
	OldValue   []byte      `json:"old_value"`
	NewValue   []byte      `json:"new_value"`
	ModifiedBy pgtype.Text `json:"modified_by"`
}

func (q *Queries) LogURLHistory(ctx context.Context, arg LogURLHistoryParams) (UrlHistory, error) {
	row := q.db.QueryRow(ctx, logURLHistory,
		arg.UrlID,
		arg.UrlShort,
		arg.Action,
		arg.OldValue,
		arg.NewValue,
		arg.ModifiedBy,
	)
	var i UrlHistory
	err := row.Scan(
		&i.ID,
		&i.UrlID,
		&i.UrlShort,
		&i.Action,
		&i.OldValue,
		&i.NewValue,
		&i.ModifiedAt,
		&i.ModifiedBy,
	)
	return i, err
}
