// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: urls.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createURL = `-- name: CreateURL :one
INSERT INTO urls (original, short, title, created_at, expires_at, clicks, creator_reference, deleted_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, original, short, title, created_at, expires_at, clicks, creator_reference, deleted_at
`

type CreateURLParams struct {
	Original         string           `json:"original"`
	Short            string           `json:"short"`
	Title            pgtype.Text      `json:"title"`
	CreatedAt        pgtype.Timestamp `json:"created_at"`
	ExpiresAt        pgtype.Timestamp `json:"expires_at"`
	Clicks           int64            `json:"clicks"`
	CreatorReference pgtype.Text      `json:"creator_reference"`
	DeletedAt        pgtype.Timestamp `json:"deleted_at"`
}

func (q *Queries) CreateURL(ctx context.Context, arg CreateURLParams) (Url, error) {
	row := q.db.QueryRow(ctx, createURL,
		arg.Original,
		arg.Short,
		arg.Title,
		arg.CreatedAt,
		arg.ExpiresAt,
		arg.Clicks,
		arg.CreatorReference,
		arg.DeletedAt,
	)
	var i Url
	err := row.Scan(
		&i.ID,
		&i.Original,
		&i.Short,
		&i.Title,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.Clicks,
		&i.CreatorReference,
		&i.DeletedAt,
	)
	return i, err
}

const getURLByOriginal = `-- name: GetURLByOriginal :one
SELECT id, original, short, title, created_at, expires_at, clicks, creator_reference, deleted_at
FROM urls
WHERE original = $1 AND deleted_at IS NULL
`

func (q *Queries) GetURLByOriginal(ctx context.Context, original string) (Url, error) {
	row := q.db.QueryRow(ctx, getURLByOriginal, original)
	var i Url
	err := row.Scan(
		&i.ID,
		&i.Original,
		&i.Short,
		&i.Title,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.Clicks,
		&i.CreatorReference,
		&i.DeletedAt,
	)
	return i, err
}

const getURLByShort = `-- name: GetURLByShort :one
SELECT id, original, short, title, created_at, expires_at, clicks, creator_reference, deleted_at
FROM urls
WHERE short = $1 AND deleted_at IS NULL
`

func (q *Queries) GetURLByShort(ctx context.Context, short string) (Url, error) {
	row := q.db.QueryRow(ctx, getURLByShort, short)
	var i Url
	err := row.Scan(
		&i.ID,
		&i.Original,
		&i.Short,
		&i.Title,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.Clicks,
		&i.CreatorReference,
		&i.DeletedAt,
	)
	return i, err
}

const getURLsByCreator = `-- name: GetURLsByCreator :many
SELECT id, original, short, title, created_at, expires_at, clicks, creator_reference, deleted_at
FROM urls
WHERE creator_reference = $1 AND deleted_at IS NULL
ORDER BY created_at DESC
`

func (q *Queries) GetURLsByCreator(ctx context.Context, creatorReference pgtype.Text) ([]Url, error) {
	rows, err := q.db.Query(ctx, getURLsByCreator, creatorReference)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Url{}
	for rows.Next() {
		var i Url
		if err := rows.Scan(
			&i.ID,
			&i.Original,
			&i.Short,
			&i.Title,
			&i.CreatedAt,
			&i.ExpiresAt,
			&i.Clicks,
			&i.CreatorReference,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const hardDeleteURL = `-- name: HardDeleteURL :execrows
DELETE FROM urls WHERE short = $1
`

func (q *Queries) HardDeleteURL(ctx context.Context, short string) (int64, error) {
	result, err := q.db.Exec(ctx, hardDeleteURL, short)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const incrementClicks = `-- name: IncrementClicks :one
UPDATE urls SET clicks = clicks + 1
WHERE short = $1 AND deleted_at IS NULL
RETURNING clicks
`

func (q *Queries) IncrementClicks(ctx context.Context, short string) (int64, error) {
	row := q.db.QueryRow(ctx, incrementClicks, short)
	var clicks int64
	err := row.Scan(&clicks)
	return clicks, err
}

const softDeleteURL = `-- name: SoftDeleteURL :execrows
UPDATE urls SET deleted_at = NOW()
WHERE short = $1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteURL(ctx context.Context, short string) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteURL, short)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const softDeleteURLWithCreator = `-- name: SoftDeleteURLWithCreator :execrows
UPDATE urls SET deleted_at = NOW()
WHERE short = $1 AND creator_reference = $2 AND deleted_at IS NULL
`

type SoftDeleteURLWithCreatorParams struct {
	Short            string      `json:"short"`
	CreatorReference pgtype.Text `json:"creator_reference"`
}

func (q *Queries) SoftDeleteURLWithCreator(ctx context.Context, arg SoftDeleteURLWithCreatorParams) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteURLWithCreator, arg.Short, arg.CreatorReference)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateURL = `-- name: UpdateURL :one
UPDATE urls SET original = $1, title = $2, expires_at = $3
WHERE short = $4 AND deleted_at IS NULL
RETURNING id, original, short, title, created_at, expires_at, clicks, creator_reference, deleted_at
`

type UpdateURLParams struct {
	Original  string           `json:"original"`
	Title     pgtype.Text      `json:"title"`
	ExpiresAt pgtype.Timestamp `json:"expires_at"`
	Short     string           `json:"short"`
}

func (q *Queries) UpdateURL(ctx context.Context, arg UpdateURLParams) (Url, error) {
	row := q.db.QueryRow(ctx, updateURL,
		arg.Original,
		arg.Title,
		arg.ExpiresAt,
		arg.Short,
	)
	var i Url
	err := row.Scan(
		&i.ID,
		&i.Original,
		&i.Short,
		&i.Title,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.Clicks,
		&i.CreatorReference,
		&i.DeletedAt,
	)
	return i, err
}

const updateURLWithCreator = `-- name: UpdateURLWithCreator :one
UPDATE urls SET original = $1, title = $2, expires_at = $3
WHERE short = $4 AND creator_reference = $5 AND deleted_at IS NULL
RETURNING id, original, short, title, created_at, expires_at, clicks, creator_reference, deleted_at
`

type UpdateURLWithCreatorParams struct {
	Original         string           `json:"original"`
	Title            pgtype.Text      `json:"title"`
	ExpiresAt        pgtype.Timestamp `json:"expires_at"`
	Short            string           `json:"short"`
	CreatorReference pgtype.Text      `json:"creator_reference"`
}

func (q *Queries) UpdateURLWithCreator(ctx context.Context, arg UpdateURLWithCreatorParams) (Url, error) {
	row := q.db.QueryRow(ctx, updateURLWithCreator,
		arg.Original,
		arg.Title,
		arg.ExpiresAt,
		arg.Short,
		arg.CreatorReference,
	)
	var i Url
	err := row.Scan(
		&i.ID,
		&i.Original,
		&i.Short,
		&i.Title,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.Clicks,
		&i.CreatorReference,
		&i.DeletedAt,
	)
	return i, err
}
